---
name: Recipe Actions

on:
  push:
    branches: [ master, dev ]

jobs:
  test-lint:
    name: Recipe API Test
    runs-on: ubuntu-20.04

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unit Test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
        run: docker-compose run --rm web sh -c "python manage.py test"
      # - name: Lint
      #   run: docker-compose run --rm web sh -c "flake8"
